#!/bin/bash

# Old runtest is broken because of DataSource.picklediff tests
# we have to run each test package in differents python instances

test_package_name='test'

for d in $(find . -type d -name "$test_package_name")
do
	echo -e "\tTesting\t$(dirname $d)\n"
	python -W ignore -m unittest discover -qf -s "$d" || break
done
